/*
 * ${classname}.java
 * Generated by XGen using control.vm
 * $now
 * package: workzen.xgen.types
 */
package workzen.xgen.types;

import java.util.*;

/**
 * $bean.getDescription()
 * @author $bean.Author
 */
public class $classname {

  /** 
   * to String 
   */
  public String toString(){
    return getDataMap().toString();
  }

  /** 
   * Get the object as a map of key-value pairs
   */
  public HashMap getDataMap(){
    HashMap map = new HashMap();
    return map;
  }
 
}




